# This is the name of the workflow, which will be displayed in the Actions tab in GitHub
name: Java CI with Maven

# This section defines when the workflow should run
on:
  push:
    branches:
      - master  # Run this workflow on pushes to the main branch
  pull_request:
    branches:
      - master  # Run this workflow on pull requests targeting the main branch

jobs:
  build:
    # The type of machine that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository code to the workflow runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to set up JDK 17 to run the Java build
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # The version of Java to install
          distribution: 'temurin'
          #Usually adopt ,temurin, corretto (Amazon) or openjdk (OpenJdk)

      # Step to build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step to run unit tests using Maven
      - name: Run Unit Tests
        run: mvn test

      #Part 2
      # Step to build a Docker image
      - name: Build Docker Image
        run: docker build -t product_pipe_image .

      # Step to log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step to push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker tag product_pipe_image ${{ secrets.DOCKER_USERNAME }}/product_pipe_image:latest \
          && docker push ${{ secrets.DOCKER_USERNAME }}/product_pipe_image:latest